services:
    sonata.admin.theme:
        class: Effi\QCMBundle\Admin\ThemeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Theme" }
        arguments:
            - ~
            - Effi\QCMBundle\Entity\Theme
            - ~
        calls:
            - [ setTranslationDomain, [EffiQCMBundle]]

    sonata.admin.choice:
        class: Effi\QCMBundle\Admin\ChoiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Choice" }
        arguments:
            - ~
            - Effi\QCMBundle\Entity\Choice
            - ~
        calls:
            - [ setTranslationDomain, [EffiQCMBundle]]
