services:
    sonata.admin.theme:
        class: Effi\QCMBundle\Admin\ThemeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Theme" }
        arguments:
            - ~
            - Effi\QCMBundle\Entity\Theme
            - ~
        calls:
            - [ setTranslationDomain, [EffiQCMBundle]]

    sonata.admin.choice:
        class: Effi\QCMBundle\Admin\ChoiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Choice" }
        arguments:
            - ~
            - Effi\QCMBundle\Entity\Choice
            - ~
        calls:
            - [ setTranslationDomain, [EffiQCMBundle]]

    sonata.admin.answer:
        class: Effi\QCMBundle\Admin\AnswerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Answer" }
        arguments:
            - ~
            - Effi\QCMBundle\Entity\Answer
            - ~
        calls:
            - [ setTranslationDomain, [EffiQCMBundle]]

    sonata.admin.question:
        class: Effi\QCMBundle\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Question" }
        arguments:
            - ~
            - Effi\QCMBundle\Entity\Question
            - ~
        calls:
            - [ setTranslationDomain, [EffiQCMBundle]]

    sonata.admin.qcm:
        class: Effi\QCMBundle\Admin\QCMAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "QCM" }
        arguments:
            - ~
            - Effi\QCMBundle\Entity\QCM
            - ~
        calls:
            - [ setTranslationDomain, [EffiQCMBundle]]
